[package]
name = "redis_module_pi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pi"
path = "src/pi.rs"
crate-type = ["dylib"]

[dependencies]
redis-module = "1.0.1"
